name: Build VSIX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: 'recursive'
    - name: Build and cache WASM dependencies
      uses: ./.github/actions/build-wasm-deps
      with:
        build-artifacts-dir: ./media
    - name: Download Slang release artifacts
      id: download-slang
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        TAGNAME="$(gh release view --repo shader-slang/slang --json tagName -q .tagName)"
        echo "version=$TAGNAME" >> "$GITHUB_OUTPUT"

        gh release download "$TAGNAME" --repo shader-slang/slang --dir . --pattern 'slang-*-windows-x86_64.zip'
        gh release download "$TAGNAME" --repo shader-slang/slang --dir . --pattern 'slang-*-windows-aarch64.zip'
        gh release download "$TAGNAME" --repo shader-slang/slang --dir . --pattern 'slang-*-linux-x86_64.zip'
        gh release download "$TAGNAME" --repo shader-slang/slang --dir . --pattern 'slang-*-linux-aarch64.zip'
        gh release download "$TAGNAME" --repo shader-slang/slang --dir . --pattern 'slang-*-macos-x86_64.zip'
        gh release download "$TAGNAME" --repo shader-slang/slang --dir . --pattern 'slang-*-macos-aarch64.zip'
    - name: Copy Slang binaries and Build VSIX
      run: |
        export TAGNAME=${{ steps.download-slang.outputs.version }}
        export WIN32_X64_ZIP=slang-${TAGNAME:1}-windows-x86_64.zip
        export WIN32_ARM64_ZIP=slang-${TAGNAME:1}-windows-aarch64.zip
        export LINUX_X64_ZIP=slang-${TAGNAME:1}-linux-x86_64.zip
        export LINUX_ARM64_ZIP=slang-${TAGNAME:1}-linux-aarch64.zip
        export DARWIN_X64_ZIP=slang-${TAGNAME:1}-macos-x86_64.zip
        export DARWIN_ARM64_ZIP=slang-${TAGNAME:1}-macos-aarch64.zip
        source ./build_scripts/build-package.sh

        for file in ./*.vsix
        do
          echo "Built VSIX: $file"
        done
    - uses: actions/upload-artifact@v7
      with:
        name: slang-vsix
        path: |
          *.vsix
